"""Golden regression vs committed simulation artifacts.

Guards the canonical 100K-user simulation outputs against silent drift. Each
JSON snapshot lives under ``data/simulation/`` (untracked — regenerated by the
DGP pipeline); the whole module is skipped when it is absent so CI without the
generated data stays green.

Assertions are deliberately *robust* — exact float values are not pinned (they
change on regeneration with a new seed). Instead we lock the qualitative,
documented invariants:
    - ground_truth.json : channel ranking (Paid Search rank-1, funnel order),
      credit normalization (Σ = 1).
    - summary_stats.json : conversion rate window, right-skewed journey length,
      per-segment conversion ordering.
    - cost_summary.json  : Paid Search dominates total spend (CPC vs CPM/fixed).
"""
from __future__ import annotations

import json
from pathlib import Path

import numpy as np
import pytest

from part1_simulation import CHANNEL_NAMES, SEGMENT_NAMES

DATA = Path("/Users/taehyun/project/mta-simulation/data/simulation")

pytestmark = pytest.mark.skipif(
    not (DATA / "ground_truth.json").exists(),
    reason="data/simulation not present (untracked)",
)


def _load(name: str) -> dict:
    with open(DATA / name) as fh:
        return json.load(fh)


# ============================================================
# 1. ground_truth.json — channel ranking + credit normalization
# ============================================================

def test_ground_truth_files_exist():
    """All three golden artifacts must be present together."""
    for name in ("ground_truth.json", "summary_stats.json", "cost_summary.json"):
        assert (DATA / name).exists(), f"missing golden artifact: {name}"


def test_gt_a_paid_search_is_rank_1():
    """GT-A (intensity_decomposition): Paid Search is the top-credited channel."""
    gt = _load("ground_truth.json")["ground_truth_A"]
    ranking = gt["channel_ranking"]
    assert ranking[0] == "Paid Search", f"GT-A rank-1 = {ranking[0]!r}"


def test_gt_a_full_documented_order():
    """GT-A ranking matches the documented canonical order.

    Paid Search > Email > Direct > Organic Search > Referral > Display > Social.
    If a future regeneration shifts a single rank, fall back to the robust
    subset in ``test_gt_a_robust_ordering`` and note the deviation.
    """
    gt = _load("ground_truth.json")["ground_truth_A"]
    expected = [
        "Paid Search",
        "Email",
        "Direct",
        "Organic Search",
        "Referral",
        "Display",
        "Social",
    ]
    assert gt["channel_ranking"] == expected, (
        f"GT-A ranking drifted: {gt['channel_ranking']}"
    )


def test_gt_a_robust_ordering():
    """Robust subset that survives minor regeneration jitter.

    Independent of exact mid-table order: Paid Search is rank-1, the two
    lower-funnel / mid-funnel leaders (Paid Search, Email) outrank the two
    weakest upper-funnel channels (Display, Social).
    """
    gt = _load("ground_truth.json")["ground_truth_A"]
    credits = gt["channel_credits"]
    assert gt["channel_ranking"][0] == "Paid Search"
    # First-funnel / strong channels dominate the weak upper-funnel pair.
    assert credits["Paid Search"] > credits["Display"]
    assert credits["Paid Search"] > credits["Social"]
    assert credits["Email"] > credits["Display"]
    assert credits["Email"] > credits["Social"]
    # Social is the single weakest channel (matches lowest beta / fast decay).
    assert credits["Social"] == min(credits.values())


def test_gt_ranking_consistent_with_credits():
    """The stored ``channel_ranking`` is the credits dict sorted descending."""
    for key in ("ground_truth_A", "ground_truth_B"):
        gt = _load("ground_truth.json")[key]
        derived = sorted(
            gt["channel_credits"], key=gt["channel_credits"].get, reverse=True
        )
        assert gt["channel_ranking"] == derived, f"{key} ranking != sorted credits"


def test_gt_credits_cover_all_channels():
    """Both GT credit dicts are keyed by exactly the 7 canonical channels."""
    gt = _load("ground_truth.json")
    for key in ("ground_truth_A", "ground_truth_B"):
        assert set(gt[key]["channel_credits"]) == set(CHANNEL_NAMES), key


def test_gt_a_credits_sum_to_one():
    """GT-A channel credits form a normalized distribution (Σ = 1)."""
    gt = _load("ground_truth.json")["ground_truth_A"]
    total = sum(gt["channel_credits"].values())
    np.testing.assert_allclose(total, 1.0, atol=1e-6)


def test_gt_b_credits_sum_to_one():
    """GT-B (counterfactual_shapley) channel credits sum to 1."""
    gt = _load("ground_truth.json")["ground_truth_B"]
    total = sum(gt["channel_credits"].values())
    np.testing.assert_allclose(total, 1.0, atol=1e-6)


def test_gt_credits_all_positive():
    """Every channel receives strictly positive credit in both GT variants."""
    gt = _load("ground_truth.json")
    for key in ("ground_truth_A", "ground_truth_B"):
        for ch, v in gt[key]["channel_credits"].items():
            assert v > 0.0, f"{key}/{ch} credit not positive: {v}"


def test_gt_b_paid_search_email_lead():
    """GT-B agrees with GT-A on the two strongest channels (Paid Search, Email)."""
    gt = _load("ground_truth.json")["ground_truth_B"]
    assert gt["channel_ranking"][0] == "Paid Search"
    assert gt["channel_ranking"][1] == "Email"


def test_gt_dgp_parameters_match_canonical_betas():
    """Stored DGP betas / etas match the canonical config values."""
    params = _load("ground_truth.json")["dgp_parameters"]
    expected_betas = {
        "Display": 0.3,
        "Social": 0.4,
        "Organic Search": 0.5,
        "Paid Search": 1.2,
        "Email": 0.8,
        "Referral": 0.5,
        "Direct": 0.7,
    }
    assert params["betas"] == expected_betas
    assert params["segment_etas"] == {"New": -0.3, "Exploratory": 0.0, "Loyal": 0.5}


# ============================================================
# 2. summary_stats.json — conversion rate, skew, segment ordering
# ============================================================

def test_summary_conversion_rate_in_window():
    """Realized conversion rate lands in the calibrated [1.5%, 4%] band."""
    ss = _load("summary_stats.json")
    cr = ss["conversion_rate"]
    assert 0.015 <= cr <= 0.04, f"conversion_rate out of band: {cr}"


def test_summary_conversion_rate_self_consistent():
    """conversion_rate == n_converted / n_users (internal consistency)."""
    ss = _load("summary_stats.json")
    np.testing.assert_allclose(
        ss["conversion_rate"], ss["n_converted"] / ss["n_users"], rtol=1e-9
    )


def test_summary_journey_length_right_skewed():
    """Journey-length distribution is strongly right-skewed (skew > 1.5)."""
    ss = _load("summary_stats.json")
    assert ss["journey_length_skew"] > 1.5, (
        f"journey_length_skew not right-skewed: {ss['journey_length_skew']}"
    )


def test_summary_journey_length_mean_exceeds_median():
    """Right-skew corollary: mean journey length > median."""
    ss = _load("summary_stats.json")
    assert ss["journey_length_mean"] > ss["journey_length_median"]


def test_summary_segment_conversion_ordering():
    """Per-segment conversion ordering: Exploratory > Loyal > New."""
    ss = _load("summary_stats.json")
    by_seg = ss["conversion_rate_by_segment"]
    assert by_seg["Exploratory"] > by_seg["Loyal"] > by_seg["New"], (
        f"segment conversion ordering violated: {by_seg}"
    )


def test_summary_segment_counts_cover_all_segments():
    """Segment counts span the 3 canonical segments and sum to n_users."""
    ss = _load("summary_stats.json")
    counts = ss["segment_counts"]
    assert set(counts) == set(SEGMENT_NAMES)
    assert sum(counts.values()) == ss["n_users"]


def test_summary_segment_proportions_match_config():
    """Segment shares match the 0.5 / 0.3 / 0.2 DGP proportions (sampling slack)."""
    ss = _load("summary_stats.json")
    counts = ss["segment_counts"]
    n = ss["n_users"]
    np.testing.assert_allclose(counts["New"] / n, 0.5, atol=0.02)
    np.testing.assert_allclose(counts["Exploratory"] / n, 0.3, atol=0.02)
    np.testing.assert_allclose(counts["Loyal"] / n, 0.2, atol=0.02)


def test_summary_no_timestamp_violations():
    """DGP must emit chronologically valid journeys (0 timestamp violations)."""
    ss = _load("summary_stats.json")
    assert ss["timestamp_violations"] == 0


# ============================================================
# 3. cost_summary.json — Paid Search dominates total spend
# ============================================================

def test_cost_paid_search_dominates_total_spend():
    """Paid Search (CPC $2.50) is >= 95% of total cost."""
    cs = _load("cost_summary.json")
    share = cs["channel_total_cost"]["Paid Search"] / cs["total_spend"]
    assert share >= 0.95, f"Paid Search cost share too low: {share}"


def test_cost_zero_cost_channels_are_free():
    """Organic Search, Referral, Direct are zero-cost observation channels."""
    cs = _load("cost_summary.json")
    for ch in ("Organic Search", "Referral", "Direct"):
        np.testing.assert_allclose(
            cs["channel_total_cost"][ch], 0.0, atol=1e-9
        )


def test_cost_total_spend_equals_channel_sum():
    """total_spend == Σ channel_total_cost (internal consistency)."""
    cs = _load("cost_summary.json")
    np.testing.assert_allclose(
        cs["total_spend"], sum(cs["channel_total_cost"].values()), rtol=1e-9
    )


def test_cost_per_conversion_consistent():
    """cost_per_conversion == total_spend / n_converters."""
    cs = _load("cost_summary.json")
    np.testing.assert_allclose(
        cs["cost_per_conversion"],
        cs["total_spend"] / cs["n_converters"],
        rtol=1e-9,
    )


def test_cost_avg_per_touchpoint_matches_config_order():
    """Avg cost/touchpoint ranks Paid Search (CPC) far above CPM/fixed channels."""
    cs = _load("cost_summary.json")
    avg = cs["channel_avg_cost_per_touchpoint"]
    assert avg["Paid Search"] > avg["Social"] > avg["Display"] > avg["Email"] > 0.0


def test_cost_summary_matches_embedded_copy():
    """summary_stats.json embeds an identical copy of cost_summary.json."""
    cs = _load("cost_summary.json")
    embedded = _load("summary_stats.json")["cost_summary"]
    assert cs == embedded, "cost_summary.json drifted from summary_stats embed"
